# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemindApplication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Cartography'
  pod 'ALTextInputBar'
  pod 'Firebase/Core'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'NVActivityIndicatorView'
  pod 'SinchVerification-Swift'
  pod 'NVActivityIndicatorView'
  # Pods for RemindApplication

end
